**IMPORTAMOS LIBRERIAS**

In [1]:
import tensorflow as tf

**1) Tipo de variable constante**

Puede ser un vector o numero de tipo flotante o entero y es una variable que no va a cambiar en toda la ejecucion de nuestra variable .

***La sintaxis seria de la siguiente forma:***

`tf.constant(['value', 'dtype=None', 'shape=None', "name='Const'", 'verify_shape=False'])`


In [3]:
tf.constant([1.0,2.0,3.0],name='constante1')

<tf.Tensor 'constante1:0' shape=(3,) dtype=float32>

**2) Tipo de variable placeholder**

Vamos a hacer uso de esta variable practicamente le vamos a decir a nuestro programa , quiero que me hagas una variable que este vacia en un inicio pero la vamos a ir llenando a medida que se vaya ejecutando nuestro codigo.

*Normalmente los placeholder lo estaremos usando para nuestras input data*

***La sintaxis seria de la siguiente forma:***

`tf.placeholder(dtype, shape=None, name=None)`

In [4]:
constanteph=tf.placeholder(tf.float32, name='constanteph')

In [5]:
print(constanteph)

Tensor("constanteph:0", dtype=float32)


In [6]:
# Note que todavia no nos sale nada "0" por que todavia no le hemos asignado un valor 

In [7]:
variable=tf.Variable(3,dtype=tf.float32,name='variable1')

In [8]:
print(variable)

<tf.Variable 'variable1:0' shape=() dtype=float32_ref>


# Creamos una matriz

In [9]:

matriz=tf.zeros([3, 4], tf.int32, name='matriz')

In [10]:
print(matriz)

Tensor("matriz:0", shape=(3, 4), dtype=int32)


# Momento de inicializar las variables 

In [11]:
inicializar=tf.global_variables_initializer()

**Creamos nuestra variable `*sess*`**

Esta variable sera la encargada de correr todo nuestra grafica computacional

In [12]:
sess=tf.Session()

In [13]:
# Ahora ya estamos listos para correr nuestra grafica computacional

In [17]:
sess.run(inicializar)

In [19]:
print(sess.run(matriz))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [20]:
print(sess.run(tf.constant([1.0,2.0,3.0],name='constante1')))

[1. 2. 3.]


# Uso del placeholder

In [21]:
constante=tf.constant([1.0,2.0,3.0],name='constante1')

In [22]:
multiplicacion=constanteph*constante

Note que nuestra variable `placeholder` debemos alimentarla con `feed_dict` en este caso un diccionario

In [28]:

print(sess.run(multiplicacion,feed_dict={constanteph:[[15.],[10.],[5.]]}))

[[15. 30. 45.]
 [10. 20. 30.]
 [ 5. 10. 15.]]


# Operaciones matriciales

***Multiplicacion de matrices necesita lleva la forma (M,N)x(N,M)=M,M***


In [29]:

# Las primeras 3 lineas de codigo son para generar nuestra grafica computacional
#-----------------------------------------
a=tf.placeholder(tf.float32, shape=(2,2))
b=tf.placeholder(tf.float32, shape=(2,3))
mult=tf.matmul(a,b)

# Las siguientes lineas de codigo son para correr nuestra grafica computacional
#-----------------------------------------
init=tf.global_variables_initializer()
sess=tf.Session()
sess.run(init)
print(sess.run(mult,feed_dict={a:[[1,2],[2,2]],b:[[12,21,4],[3,2,4]] }))

[[18. 25. 12.]
 [30. 46. 16.]]


 ***Producto punto entre 2 vectores R3***

In [30]:
c=tf.placeholder(tf.float32, shape=(3))
d=tf.placeholder(tf.float32, shape=(3))
punto=tf.tensordot(c,d,1)
init=tf.global_variables_initializer()
sess=tf.Session()
sess.run(init)
print(sess.run(punto,feed_dict={c:[1,2,3],d:[3,2,1]}))

10.0
